### ISSUE TITLE
TypeError: murlock_1.MurLockService.unlock is not a function

### ISSUE THREAD

**Issue by ahtinurme** [felanios/murlock#13]
When using the service in NestJS:

```
import { MurLockService } from 'murlock';
...
await MurLockService.lock('function1');
```

 I get this:

`TypeError: murlock_1.MurLockService.unlock is not a function`

version 1.2.1

**Comment by felanios** [comment]
@ahtinurme Hi, directly usage of MurLockService and documentation for that not clear I agree. I'll make a improvement for that, fyi.
