### ISSUE TITLE
Feature request: Ability to lock the same key from different services (or methods) via Lock decorator.

### ISSUE THREAD

**Issue by OsoianMarcel** [felanios/murlock#21]
**Problem:**
I have a resource (for example, ID 123), so I need a distributed lock across different applications and different services.
Currently, the Murlock decorator generates a lock key that includes the service name and method name as part of the lock key, so I can not lock the same resource (ID 123) with different service names or different method names because the lock key will be different.
I know this was made by design. 
It would be great to have another lock decorator where the lock key does not include the service name and method name, so the user would have full control over the lock key name.
I'm aware that I can directly utilize the lock service, but employing a TypeScript Decorator would add a touch of elegance.

**Some ideas:**
- Add an optional setting for the actual Murlock decorator to remove the service name and method name from the lock key, and use a different lock key prefix. Example: `{lockPrefix?: string}` (is the setting is optional, it can be back compatible);
- Create a new Murlock decorator that will not include the service name and method name (easy, and 100% back compatible);
- A new Murlock decorator with a closure function, where in the parameters we can access the method parameters, and some another props (some injection maybe?).

Thank you.

**Comment by felanios** [comment]
Hi @OsoianMarcel, thank you for your feedback and support, I will look at the feature you want and take care of it as soon as possible.

**Comment by felanios** [comment]
Hi @OsoianMarcel, I couldn't look at the package due to work, but I haven't forgotten your request. I'll take care of it as soon as I get the chance, I just wanted to keep you informed.

**Comment by ledmago** [comment]
Hey @OsoianMarcel, The new version is released. you can use lockKeyPrefix in the root of module 🙌🏻
