### ISSUE TITLE
Refactor: change the module configuration method name [register] to [forRoot]

### ISSUE THREAD

**Issue by OsoianMarcel** [felanios/murlock#22]
According to [NestJS Community guidelines](https://docs.nestjs.com/fundamentals/dynamic-modules#community-guidelines), the global modules should be configured with the method **forRoot / forRootAsync**.

- **register** - expecting to configure a dynamic module with a specific configuration for use only by the calling module.
- **forRoot** - you are expecting to configure a dynamic module once and reuse that configuration in multiple places.

It would be nice to follow NestJS community guidelines.

**Comment by felanios** [comment]
Hi @OsoianMarcel, thanks for feedback. This week I'll publish a new version.

**Comment by felanios** [comment]
Hi @OsoianMarcel, I published the beta version for this changes. You can check this `3.0.0-beta.1`

**Comment by felanios** [comment]
Hi @OsoianMarcel, I published the stable version `3.0.0`
