### ISSUE TITLE
Could we not throw an exception on release?

### ISSUE THREAD

**Issue by Scoup** [felanios/murlock#34]
I have a low latency project, usually with ttl below 500ms, but sometimes we have spikes, and when this happens the [flow is broken](https://github.com/felanios/murlock/blob/master/lib/murlock.service.ts#L116-L128) because the service can't release the key (because it already expired with TTL).
I don't know why my application would throw an error when trying to release a key (the app can't recover from this).
Can we at least have this throw as optional? I could open a PR with this option.

**Comment by felanios** [comment]
Hi @Scoup, yeap we can make optional to throw unlock side.

**Comment by ssijak** [comment]
@Scoup you can just do `.catch(ex => {...})` and swallow the exception on release or just log it

**Comment by felanios** [comment]
Hi @Scoup, I added a flag named `ignoreUnlockFail` to handle your request. If it's `true` unlock method's exception will be only logged. You can check this version https://www.npmjs.com/package/murlock/v/3.1.0

**Comment by Scoup** [comment]
@felanios thanks for the update!!
